"""initial_db

Revision ID: 050b667d6853
Revises: 
Create Date: 2021-07-12 22:46:08.628733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '050b667d6853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_together_room',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('film_work_uuid', postgresql.UUID(), nullable=True),
    sa.Column('film_work_time', sa.Float(), nullable=True),
    sa.Column('film_work_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cinema_together_room_user',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('room_uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['room_uuid'], ['cinema_together_room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'room_uuid', name='unique_room_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_together_room_user')
    op.drop_table('cinema_together_room')
    # ### end Alembic commands ###
