"""added_owner_to_room

Revision ID: 67684bfb026f
Revises: 050b667d6853
Create Date: 2021-07-16 20:45:06.773741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67684bfb026f'
down_revision = '050b667d6853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema_together_room', sa.Column('owner_uuid', postgresql.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cinema_together_room', 'owner_uuid')
    # ### end Alembic commands ###
