"""added unique to room owner id

Revision ID: be39f607c24f
Revises: 820358d10786
Create Date: 2021-07-20 19:07:45.631281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be39f607c24f'
down_revision = '820358d10786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cinema_together_room', ['owner_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cinema_together_room', type_='unique')
    # ### end Alembic commands ###
